### ISSUE TITLE
Rejecting partially initialized sublayer (sublayerbuilder.cpp: 86)

### ISSUE THREAD

**Issue by youliso** [mullvad/libwfp#25]
Rejecting partially initialized sublayer (sublayerbuilder.cpp: 86)

**Comment by mvd-ows** [comment]
You can configure structure verification by passing a suitable flag to the SublayerBuilder ctor. This adjusts the amount of verification that's done on the settings before building an object.

If you feel the exception is in error you'll need to provide more data.

**Comment by youliso** [comment]
Thank you for your answer.
I don't know much about C + +. Would you please compile a Windows 10 x64 exe?
Similar to this (command line start):
wfp.exe - “name.exe,name.exe”  - port
That's how it starts

**Comment by mvd-ows** [comment]
In that case you're looking at the wrong repository. `libwfp` is only a library that provides the building blocks for something like the `wfp.exe` tool you're mentioning.
